# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a0730e7241468f14b24c086cca86f826b68ce7fe4ed84b1404c7aff7015e4fe6620b83aa014770f1d631fcb03255e19b999d9d7f920f6d1a155a5484353028

test:
  secret_key_base: 3c027ce9947fb5490e19ab1972decd92aa7f15fa0001b95c8367ca436159c89d1099924dc0905139a8da202f82fce8c71a9a820987cf161cd6f7bb6c0072b2e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
